### ISSUE TITLE
Broken arrows on conversion

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/uv2etl#1]
I used `uv2etl` to convert the UV v.2.3 pipeline of [Municipality of Athens Expenditure Budget 2005](https://github.com/openbudgets/datasets/raw/master/greek-municipalities/municipality-of-athens/pipelines/Municipality%20of%20Athens%20Budget%20expenses%202005.zip). The conversion outputs the following log message:

```
C:\okf\uv2etl\target>java -jar uv2lp.jar -i "Municipality of Athens Budget expenses 2005.zip"
WARN  SparqlConstructConfig_V1 - [uv-t-sparqlConstruct2] : Per graph mode ignored.
WARN  SparqlUpdateConfig_V1 - [Mutli white space...] : Per graph mode ignored.
INFO  RdfGraphMergerConfig_V1 - [uv-t-rdfGraphMerger] : Graph name ignored.
WARN  SparqlUpdateConfig_V1 - [uv-t-sparqlUpdate] : Per graph mode ignored.
INFO  FilesDownloadConfig_V1 - [uv-e-filesDownload] : Custom time out is not supported.
WARN  FilesToRDFConfig_V1 - [uv-t-filesToRdf] : Multiple outputs graphs will be merged.
WARN  SparqlUpdateConfig_V1 - [uv-t-sparqlUpdate] : Per graph mode ignored.
WARN  SparqlUpdateConfig_V1 - [Missing values st...] : Per graph mode ignored.
WARN  DatasetMetadataConfig_V1 - [E-DatasetMetadata] : 'useDatasetURIfromInput' ignored.
WARN  SparqlUpdateConfig_V1 - [uv-t-sparqlUpdate] : Per graph mode ignored.
INFO  FilesDownloadConfig_V1 - [uv-e-filesDownload] : Custom time out is not supported.
INFO  FilesDownloadConfig_V1 - [uv-e-filesDownload] : Custom time out is not supported.
WARN  FilesToRDFConfig_V1 - [uv-t-filesToRdf] : Multiple outputs graphs will be merged.
WARN  FilesToRDFConfig_V1 - [uv-t-filesToRdf] : Multiple outputs graphs will be merged.
```

Then I imported the converted pipeline int [LinkedPipes ETL Demo](http://demo.etl.linkedpipes.com/resources/pipelines/created-1461960047791) . There I can see that some arrows are broken meaning the conversion was not succesfull. I think the problem is with `rdf-graph-merger`. 

![image](https://cloud.githubusercontent.com/assets/2419820/14928805/c42b60f2-0e62-11e6-9e8c-bd21ed84e70b.png)

I have for comparison open the exact pipeline for UV and seems that the missing arrows have to do with this particular DPU. 
![image](https://cloud.githubusercontent.com/assets/2419820/14928654/fa3890a8-0e61-11e6-9803-c7df8bf8e094.png)

In the meantime I will make the corrections manually and test the pipeline.

**Comment by skarampatakis** [comment]
It seems that Graph Merger cannot accept multiple inputs.

**Comment by skodapetr** [comment]
The uv-t-rdfGraphMerger equivalent t-graphUnion is actually missing on the demo instance as it has been added after the last redeploy. Redeploy on demo (or deploy from develop branch) should work fine with the Municipality of Athens Budget expenses 2005 pipeline.

**Comment by skarampatakis** [comment]
I tried to deploy locally latest develop branch of LP but this dependecy breaks the installation

```
 [get] Getting: http://uv.opendata.cz/osgi/sesame/sesame-runtime-osgi-4.0.1-SNAPSHOT-custom.jar
      [get] To: C:\okf\etl\deploy\osgi\external\sesame-runtime-osgi-4.0.1-SNAPSHOT-custom.jar
      [get] Error getting http://uv.opendata.cz/osgi/sesame/sesame-runtime-osgi-4.0.1-SNAPSHOT-custom.jar to C:\okf\etl\deploy\osgi\external\sesame-runtime-osgi-4.0.1-SNAPSHOT-custom.jar
```

**Comment by skodapetr** [comment]
Well it looks like we have some problems with one of our server that is hosting this dependency :( so you may either wait some time for the server to become available again or if you have this file from previous build (and you should as it was not added as a new one in develop) comment out the get command starting at https://github.com/linkedpipes/etl/blob/master/deploy-dependencies/pom.xml#L415

**Comment by skarampatakis** [comment]
Unfortunately this is actual the first time I deploy LP on my machine so I don't have it. I have to w8 then or if you could provide a Dropbox link or something I would be grateful!

**Comment by skodape** [comment]
Link to the Dropbox:
https://dl.dropboxusercontent.com/u/44890049/LinkedPipes/sesame-runtime-osgi-4.0.1-SNAPSHOT-custom.jar

**Comment by jakubklimek** [comment]
`uv.opendata.cz` did not survive VM migration, so I had to reboot it, now it runs and the lp-etl maven build works.
I updated http://demo.etl.linkedpipes.com, so you can try again.

**Comment by skarampatakis** [comment]
@jakubklimek @skodape Thank you all. I have managed to build LP locally. The pipeline seems to be working and the produced file seems to be identical with the one produced by UV pipeline.
