### ISSUE TITLE
Converted JSONLD Pipeline Results in Empty Pipeline on LP interface

### ISSUE THREAD

**Issue by fathoni** [linkedpipes/uv2etl#3]
Hi all,  I am experimenting with the current state (May 9th, 15:15) version of UV2LP. I tried to convert a pipeline here https://dl.dropboxusercontent.com/u/23550208/EstructuraOrganica.zip (based on DPUs from UV 2.3) . I got the JSONLD file with the following output from console: 

`me@laptop ~/Git/uv2etl/target $ java -jar uv2lp.jar -i EstructuraOrganica.zip -o EstructuraOrganica.jsonld
WARN  SparqlUpdateConfig_V1 - [uv-t-sparqlUpdate] : Per graph mode ignored.
WARN  SparqlConstructConfig_V1 - [uv-t-sparqlConstr...] : Per graph mode ignored.
INFO  FilesFilterConfig_V1 - [uv-t-filesFilter] : Check file name pattern: Estructura Organica.csv 
WARN  FilesFilterConfig_V1 - [uv-t-filesFilter] : Symblic name no longer exists.
WARN  SparqlConstructConfig_V1 - [uv-t-sparqlConstruct] : Per graph mode ignored.
INFO  RdfGraphMergerConfig_V1 - [uv-t-rdfGraphMerger] : Graph name ignored.
INFO  FilesDownloadConfig_V1 - [uv-e-filesDownload] : Custom time out is not supported.
WARN  SparqlConstructConfig_V1 - [uv-t-sparqlConstruct] : Per graph mode ignored`

However, when I upload the JSONLD pipeline to LP-ETL, it provides an empty pipeline. Do you have any pointer on what could be the issue?

**Comment by skodapetr** [comment]
Does other pipelines work - can you create a pipeline and add a component?

**Comment by fathoni** [comment]
Hi @skodape , yes, I can create a pipeline and add the component.

**Comment by skodapetr** [comment]
Do you use master od develop branch? 

If you open the developer console do you see some warnings errors (visible message for missing components was added recently so it may not be in your version).

**Comment by fathoni** [comment]
It is the indeed the problem of the version that I've used. Thank you for your assistance!
