### ISSUE TITLE
DPU request: relational DPU

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/uv2etl#7]
It would be nice if relationalToRDF and similar DPUs could be available.

**Comment by jakubklimek** [comment]
Actually, this is a component request, could you create an issue in the linkedpipes/etl repo? And please be specific about the components requested. While a component for extraction of data from a relational database (e.g. through Direct Mapping or R2RML standards) is something we could definitely use, support for relational data inside the pipeline is not something we are planning to do.

**Comment by skarampatakis** [comment]
OK Jakub. I will close this one.
